///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CharacterIdDataResultsEvents {
/*
{
  "available": 0,
  "collectionURI": "http://gateway.marvel.com/v1/public/series/31445/events",
  "items": "[]",
  "returned": 0
} 
*/

  int? available;
  String? collectionURI;
  String? items;
  int? returned;

  CharacterIdDataResultsEvents({
    this.available,
    this.collectionURI,
    this.items,
    this.returned,
  });
  CharacterIdDataResultsEvents.fromJson(Map<String, dynamic> json) {
    available = json['available']?.toInt();
    collectionURI = json['collectionURI']?.toString();
    items = json['items']?.toString();
    returned = json['returned']?.toInt();
  }

  get code => null;
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['available'] = available;
    data['collectionURI'] = collectionURI;
    data['items'] = items;
    data['returned'] = returned;
    return data;
  }
}

class CharacterIdDataResultsComicsItems {
/*
{
  "resourceURI": "http://gateway.marvel.com/v1/public/comics/91992",
  "name": " Fantastic Four by Dan Slott Vol. 1 (Hardcover)"
} 
*/

  String? resourceURI;
  String? name;

  CharacterIdDataResultsComicsItems({
    this.resourceURI,
    this.name,
  });
  CharacterIdDataResultsComicsItems.fromJson(Map<String, dynamic> json) {
    resourceURI = json['resourceURI']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['resourceURI'] = resourceURI;
    data['name'] = name;
    return data;
  }
}

class CharacterIdDataResultsComics {
/*
{
  "available": 1,
  "collectionURI": "http://gateway.marvel.com/v1/public/series/31445/comics",
  "items": [
    {
      "resourceURI": "http://gateway.marvel.com/v1/public/comics/91992",
      "name": " Fantastic Four by Dan Slott Vol. 1 (Hardcover)"
    }
  ],
  "returned": 1
} 
*/

  int? available;
  String? collectionURI;
  List<CharacterIdDataResultsComicsItems?>? items;
  int? returned;

  CharacterIdDataResultsComics({
    this.available,
    this.collectionURI,
    this.items,
    this.returned,
  });
  CharacterIdDataResultsComics.fromJson(Map<String, dynamic> json) {
    available = json['available']?.toInt();
    collectionURI = json['collectionURI']?.toString();
    if (json['items'] != null) {
      final v = json['items'];
      final arr0 = <CharacterIdDataResultsComicsItems>[];
      v.forEach((v) {
        arr0.add(CharacterIdDataResultsComicsItems.fromJson(v));
      });
      items = arr0;
    }
    returned = json['returned']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['available'] = available;
    data['collectionURI'] = collectionURI;
    if (items != null) {
      final v = items;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['items'] = arr0;
    }
    data['returned'] = returned;
    return data;
  }
}

class CharacterIdDataResultsStoriesItems {
/*
{
  "resourceURI": "http://gateway.marvel.com/v1/public/stories/205070",
  "name": "cover from FANTASTIC FOUR BY DAN SLOTT VOL. 1 HC (2021) #1",
  "type": "cover"
} 
*/

  String? resourceURI;
  String? name;
  String? type;

  CharacterIdDataResultsStoriesItems({
    this.resourceURI,
    this.name,
    this.type,
  });
  CharacterIdDataResultsStoriesItems.fromJson(Map<String, dynamic> json) {
    resourceURI = json['resourceURI']?.toString();
    name = json['name']?.toString();
    type = json['type']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['resourceURI'] = resourceURI;
    data['name'] = name;
    data['type'] = type;
    return data;
  }
}

class CharacterIdDataResultsStories {
/*
{
  "available": 2,
  "collectionURI": "http://gateway.marvel.com/v1/public/series/31445/stories",
  "items": [
    {
      "resourceURI": "http://gateway.marvel.com/v1/public/stories/205070",
      "name": "cover from FANTASTIC FOUR BY DAN SLOTT VOL. 1 HC (2021) #1",
      "type": "cover"
    }
  ],
  "returned": 2
} 
*/

  int? available;
  String? collectionURI;
  List<CharacterIdDataResultsStoriesItems?>? items;
  int? returned;

  CharacterIdDataResultsStories({
    this.available,
    this.collectionURI,
    this.items,
    this.returned,
  });
  CharacterIdDataResultsStories.fromJson(Map<String, dynamic> json) {
    available = json['available']?.toInt();
    collectionURI = json['collectionURI']?.toString();
    if (json['items'] != null) {
      final v = json['items'];
      final arr0 = <CharacterIdDataResultsStoriesItems>[];
      v.forEach((v) {
        arr0.add(CharacterIdDataResultsStoriesItems.fromJson(v));
      });
      items = arr0;
    }
    returned = json['returned']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['available'] = available;
    data['collectionURI'] = collectionURI;
    if (items != null) {
      final v = items;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['items'] = arr0;
    }
    data['returned'] = returned;
    return data;
  }
}

class CharacterIdDataResultsCharacters {
/*
{
  "available": 0,
  "collectionURI": "http://gateway.marvel.com/v1/public/series/31445/characters",
  "items": "[]",
  "returned": 0
} 
*/

  int? available;
  String? collectionURI;
  String? items;
  int? returned;

  CharacterIdDataResultsCharacters({
    this.available,
    this.collectionURI,
    this.items,
    this.returned,
  });
  CharacterIdDataResultsCharacters.fromJson(Map<String, dynamic> json) {
    available = json['available']?.toInt();
    collectionURI = json['collectionURI']?.toString();
    items = json['items']?.toString();
    returned = json['returned']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['available'] = available;
    data['collectionURI'] = collectionURI;
    data['items'] = items;
    data['returned'] = returned;
    return data;
  }
}

class CharacterIdDataResultsCreatorsItems {
/*
{
  "resourceURI": "http://gateway.marvel.com/v1/public/creators/4430",
  "name": "Jeff Youngquist",
  "role": "editor"
} 
*/

  String? resourceURI;
  String? name;
  String? role;

  CharacterIdDataResultsCreatorsItems({
    this.resourceURI,
    this.name,
    this.role,
  });
  CharacterIdDataResultsCreatorsItems.fromJson(Map<String, dynamic> json) {
    resourceURI = json['resourceURI']?.toString();
    name = json['name']?.toString();
    role = json['role']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['resourceURI'] = resourceURI;
    data['name'] = name;
    data['role'] = role;
    return data;
  }
}

class CharacterIdDataResultsCreators {
/*
{
  "available": 1,
  "collectionURI": "http://gateway.marvel.com/v1/public/series/31445/creators",
  "items": [
    {
      "resourceURI": "http://gateway.marvel.com/v1/public/creators/4430",
      "name": "Jeff Youngquist",
      "role": "editor"
    }
  ],
  "returned": 1
} 
*/

  int? available;
  String? collectionURI;
  List<CharacterIdDataResultsCreatorsItems?>? items;
  int? returned;

  CharacterIdDataResultsCreators({
    this.available,
    this.collectionURI,
    this.items,
    this.returned,
  });
  CharacterIdDataResultsCreators.fromJson(Map<String, dynamic> json) {
    available = json['available']?.toInt();
    collectionURI = json['collectionURI']?.toString();
    if (json['items'] != null) {
      final v = json['items'];
      final arr0 = <CharacterIdDataResultsCreatorsItems>[];
      v.forEach((v) {
        arr0.add(CharacterIdDataResultsCreatorsItems.fromJson(v));
      });
      items = arr0;
    }
    returned = json['returned']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['available'] = available;
    data['collectionURI'] = collectionURI;
    if (items != null) {
      final v = items;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['items'] = arr0;
    }
    data['returned'] = returned;
    return data;
  }
}

class CharacterIdDataResultsThumbnail {
/*
{
  "path": "http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available",
  "extension": "jpg"
} 
*/

  String? path;
  String? extension;

  CharacterIdDataResultsThumbnail({
    this.path,
    this.extension,
  });
  CharacterIdDataResultsThumbnail.fromJson(Map<String, dynamic> json) {
    path = json['path']?.toString();
    extension = json['extension']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['path'] = path;
    data['extension'] = extension;
    return data;
  }
}

class CharacterIdDataResultsUrls {
/*
{
  "type": "detail",
  "url": "http://marvel.com/comics/series/31445/_fantastic_four_by_dan_slott_vol_1_2021?utm_campaign=apiRef&utm_source=edc015b686b72ca236f9a3a730613076"
} 
*/

  String? type;
  String? url;

  CharacterIdDataResultsUrls({
    this.type,
    this.url,
  });
  CharacterIdDataResultsUrls.fromJson(Map<String, dynamic> json) {
    type = json['type']?.toString();
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    data['url'] = url;
    return data;
  }
}

class CharacterIdDataResults {
/*
{
  "id": 31445,
  "title": " Fantastic Four by Dan Slott Vol. 1 (2021)",
  "description": "null",
  "resourceURI": "http://gateway.marvel.com/v1/public/series/31445",
  "urls": [
    {
      "type": "detail",
      "url": "http://marvel.com/comics/series/31445/_fantastic_four_by_dan_slott_vol_1_2021?utm_campaign=apiRef&utm_source=edc015b686b72ca236f9a3a730613076"
    }
  ],
  "startYear": 2021,
  "endYear": 2021,
  "rating": "",
  "type": "collection",
  "modified": "2020-07-29T09:04:18-0400",
  "thumbnail": {
    "path": "http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available",
    "extension": "jpg"
  },
  "creators": {
    "available": 1,
    "collectionURI": "http://gateway.marvel.com/v1/public/series/31445/creators",
    "items": [
      {
        "resourceURI": "http://gateway.marvel.com/v1/public/creators/4430",
        "name": "Jeff Youngquist",
        "role": "editor"
      }
    ],
    "returned": 1
  },
  "characters": {
    "available": 0,
    "collectionURI": "http://gateway.marvel.com/v1/public/series/31445/characters",
    "items": "[]",
    "returned": 0
  },
  "stories": {
    "available": 2,
    "collectionURI": "http://gateway.marvel.com/v1/public/series/31445/stories",
    "items": [
      {
        "resourceURI": "http://gateway.marvel.com/v1/public/stories/205070",
        "name": "cover from FANTASTIC FOUR BY DAN SLOTT VOL. 1 HC (2021) #1",
        "type": "cover"
      }
    ],
    "returned": 2
  },
  "comics": {
    "available": 1,
    "collectionURI": "http://gateway.marvel.com/v1/public/series/31445/comics",
    "items": [
      {
        "resourceURI": "http://gateway.marvel.com/v1/public/comics/91992",
        "name": " Fantastic Four by Dan Slott Vol. 1 (Hardcover)"
      }
    ],
    "returned": 1
  },
  "events": {
    "available": 0,
    "collectionURI": "http://gateway.marvel.com/v1/public/series/31445/events",
    "items": "[]",
    "returned": 0
  },
  "next": "null",
  "previous": "null"
} 
*/

  int? id;
  String? title;
  String? description;
  String? resourceURI;
  List<CharacterIdDataResultsUrls?>? urls;
  int? startYear;
  int? endYear;
  String? rating;
  String? type;
  String? modified;
  CharacterIdDataResultsThumbnail? thumbnail;
  CharacterIdDataResultsCreators? creators;
  CharacterIdDataResultsCharacters? characters;
  CharacterIdDataResultsStories? stories;
  CharacterIdDataResultsComics? comics;
  CharacterIdDataResultsEvents? events;
  String? next;
  String? previous;

  CharacterIdDataResults({
    this.id,
    this.title,
    this.description,
    this.resourceURI,
    this.urls,
    this.startYear,
    this.endYear,
    this.rating,
    this.type,
    this.modified,
    this.thumbnail,
    this.creators,
    this.characters,
    this.stories,
    this.comics,
    this.events,
    this.next,
    this.previous,
  });
  CharacterIdDataResults.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
    description = json['description']?.toString();
    resourceURI = json['resourceURI']?.toString();
    if (json['urls'] != null) {
      final v = json['urls'];
      final arr0 = <CharacterIdDataResultsUrls>[];
      v.forEach((v) {
        arr0.add(CharacterIdDataResultsUrls.fromJson(v));
      });
      urls = arr0;
    }
    startYear = json['startYear']?.toInt();
    endYear = json['endYear']?.toInt();
    rating = json['rating']?.toString();
    type = json['type']?.toString();
    modified = json['modified']?.toString();
    thumbnail = (json['thumbnail'] != null)
        ? CharacterIdDataResultsThumbnail.fromJson(json['thumbnail'])
        : null;
    creators = (json['creators'] != null)
        ? CharacterIdDataResultsCreators.fromJson(json['creators'])
        : null;
    characters = (json['characters'] != null)
        ? CharacterIdDataResultsCharacters.fromJson(json['characters'])
        : null;
    stories = (json['stories'] != null)
        ? CharacterIdDataResultsStories.fromJson(json['stories'])
        : null;
    comics = (json['comics'] != null)
        ? CharacterIdDataResultsComics.fromJson(json['comics'])
        : null;
    events = (json['events'] != null)
        ? CharacterIdDataResultsEvents.fromJson(json['events'])
        : null;
    next = json['next']?.toString();
    previous = json['previous']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['description'] = description;
    data['resourceURI'] = resourceURI;
    if (urls != null) {
      final v = urls;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['urls'] = arr0;
    }
    data['startYear'] = startYear;
    data['endYear'] = endYear;
    data['rating'] = rating;
    data['type'] = type;
    data['modified'] = modified;
    if (thumbnail != null) {
      data['thumbnail'] = thumbnail!.toJson();
    }
    if (creators != null) {
      data['creators'] = creators!.toJson();
    }
    if (characters != null) {
      data['characters'] = characters!.toJson();
    }
    if (stories != null) {
      data['stories'] = stories!.toJson();
    }
    if (comics != null) {
      data['comics'] = comics!.toJson();
    }
    if (events != null) {
      data['events'] = events!.toJson();
    }
    data['next'] = next;
    data['previous'] = previous;
    return data;
  }
}

class CharacterIdData {
/*
{
  "offset": 0,
  "limit": 20,
  "total": 13008,
  "count": 20,
  "results": [
    {
      "id": 31445,
      "title": " Fantastic Four by Dan Slott Vol. 1 (2021)",
      "description": "null",
      "resourceURI": "http://gateway.marvel.com/v1/public/series/31445",
      "urls": [
        {
          "type": "detail",
          "url": "http://marvel.com/comics/series/31445/_fantastic_four_by_dan_slott_vol_1_2021?utm_campaign=apiRef&utm_source=edc015b686b72ca236f9a3a730613076"
        }
      ],
      "startYear": 2021,
      "endYear": 2021,
      "rating": "",
      "type": "collection",
      "modified": "2020-07-29T09:04:18-0400",
      "thumbnail": {
        "path": "http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available",
        "extension": "jpg"
      },
      "creators": {
        "available": 1,
        "collectionURI": "http://gateway.marvel.com/v1/public/series/31445/creators",
        "items": [
          {
            "resourceURI": "http://gateway.marvel.com/v1/public/creators/4430",
            "name": "Jeff Youngquist",
            "role": "editor"
          }
        ],
        "returned": 1
      },
      "characters": {
        "available": 0,
        "collectionURI": "http://gateway.marvel.com/v1/public/series/31445/characters",
        "items": "[]",
        "returned": 0
      },
      "stories": {
        "available": 2,
        "collectionURI": "http://gateway.marvel.com/v1/public/series/31445/stories",
        "items": [
          {
            "resourceURI": "http://gateway.marvel.com/v1/public/stories/205070",
            "name": "cover from FANTASTIC FOUR BY DAN SLOTT VOL. 1 HC (2021) #1",
            "type": "cover"
          }
        ],
        "returned": 2
      },
      "comics": {
        "available": 1,
        "collectionURI": "http://gateway.marvel.com/v1/public/series/31445/comics",
        "items": [
          {
            "resourceURI": "http://gateway.marvel.com/v1/public/comics/91992",
            "name": " Fantastic Four by Dan Slott Vol. 1 (Hardcover)"
          }
        ],
        "returned": 1
      },
      "events": {
        "available": 0,
        "collectionURI": "http://gateway.marvel.com/v1/public/series/31445/events",
        "items": "[]",
        "returned": 0
      },
      "next": "null",
      "previous": "null"
    }
  ]
} 
*/

  int? offset;
  int? limit;
  int? total;
  int? count;
  List<CharacterIdDataResults?>? results;

  CharacterIdData({
    this.offset,
    this.limit,
    this.total,
    this.count,
    this.results,
  });
  CharacterIdData.fromJson(Map<String, dynamic> json) {
    offset = json['offset']?.toInt();
    limit = json['limit']?.toInt();
    total = json['total']?.toInt();
    count = json['count']?.toInt();
    if (json['results'] != null) {
      final v = json['results'];
      final arr0 = <CharacterIdDataResults>[];
      v.forEach((v) {
        arr0.add(CharacterIdDataResults.fromJson(v));
      });
      results = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['offset'] = offset;
    data['limit'] = limit;
    data['total'] = total;
    data['count'] = count;
    if (results != null) {
      final v = results;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['results'] = arr0;
    }
    return data;
  }
}

class CharacterId {
/*
{
  "code": 200,
  "status": "Ok",
  "copyright": "© 2022 MARVEL",
  "attributionText": "Data provided by Marvel. © 2022 MARVEL",
  "attributionHTML": "<a href=\"http://marvel.com\">Data provided by Marvel. © 2022 MARVEL</a>",
  "etag": "3d20d5c97c07b6322b290c70f82bb6bf04bd15df",
  "data": {
    "offset": 0,
    "limit": 20,
    "total": 13008,
    "count": 20,
    "results": [
      {
        "id": 31445,
        "title": " Fantastic Four by Dan Slott Vol. 1 (2021)",
        "description": "null",
        "resourceURI": "http://gateway.marvel.com/v1/public/series/31445",
        "urls": [
          {
            "type": "detail",
            "url": "http://marvel.com/comics/series/31445/_fantastic_four_by_dan_slott_vol_1_2021?utm_campaign=apiRef&utm_source=edc015b686b72ca236f9a3a730613076"
          }
        ],
        "startYear": 2021,
        "endYear": 2021,
        "rating": "",
        "type": "collection",
        "modified": "2020-07-29T09:04:18-0400",
        "thumbnail": {
          "path": "http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available",
          "extension": "jpg"
        },
        "creators": {
          "available": 1,
          "collectionURI": "http://gateway.marvel.com/v1/public/series/31445/creators",
          "items": [
            {
              "resourceURI": "http://gateway.marvel.com/v1/public/creators/4430",
              "name": "Jeff Youngquist",
              "role": "editor"
            }
          ],
          "returned": 1
        },
        "characters": {
          "available": 0,
          "collectionURI": "http://gateway.marvel.com/v1/public/series/31445/characters",
          "items": "[]",
          "returned": 0
        },
        "stories": {
          "available": 2,
          "collectionURI": "http://gateway.marvel.com/v1/public/series/31445/stories",
          "items": [
            {
              "resourceURI": "http://gateway.marvel.com/v1/public/stories/205070",
              "name": "cover from FANTASTIC FOUR BY DAN SLOTT VOL. 1 HC (2021) #1",
              "type": "cover"
            }
          ],
          "returned": 2
        },
        "comics": {
          "available": 1,
          "collectionURI": "http://gateway.marvel.com/v1/public/series/31445/comics",
          "items": [
            {
              "resourceURI": "http://gateway.marvel.com/v1/public/comics/91992",
              "name": " Fantastic Four by Dan Slott Vol. 1 (Hardcover)"
            }
          ],
          "returned": 1
        },
        "events": {
          "available": 0,
          "collectionURI": "http://gateway.marvel.com/v1/public/series/31445/events",
          "items": "[]",
          "returned": 0
        },
        "next": "null",
        "previous": "null"
      }
    ]
  }
} 
*/

  int? code;
  String? status;
  String? copyright;
  String? attributionText;
  String? attributionHTML;
  String? etag;
  CharacterIdData? data;

  CharacterId({
    this.code,
    this.status,
    this.copyright,
    this.attributionText,
    this.attributionHTML,
    this.etag,
    this.data,
  });
  CharacterId.fromJson(Map<String, dynamic> json) {
    code = json['code']?.toInt();
    status = json['status']?.toString();
    copyright = json['copyright']?.toString();
    attributionText = json['attributionText']?.toString();
    attributionHTML = json['attributionHTML']?.toString();
    etag = json['etag']?.toString();
    data =
        (json['data'] != null) ? CharacterIdData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    data['status'] = status;
    data['copyright'] = copyright;
    data['attributionText'] = attributionText;
    data['attributionHTML'] = attributionHTML;
    data['etag'] = etag;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
