///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MarvelResultDataResultsUrls {
/*
{
  "type": "detail",
  "url": "http://marvel.com/comics/characters/1011334/3-d_man?utm_campaign=apiRef&utm_source=edc015b686b72ca236f9a3a730613076"
} 
*/

  String? type;
  String? url;

  MarvelResultDataResultsUrls({
    this.type,
    this.url,
  });
  MarvelResultDataResultsUrls.fromJson(Map<String, dynamic> json) {
    type = json['type']?.toString();
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    data['url'] = url;
    return data;
  }
}

class MarvelResultDataResultsEventsItems {
/*
{
  "resourceURI": "http://gateway.marvel.com/v1/public/events/269",
  "name": "Secret Invasion"
} 
*/

  String? resourceURI;
  String? name;

  MarvelResultDataResultsEventsItems({
    this.resourceURI,
    this.name,
  });
  MarvelResultDataResultsEventsItems.fromJson(Map<String, dynamic> json) {
    resourceURI = json['resourceURI']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['resourceURI'] = resourceURI;
    data['name'] = name;
    return data;
  }
}

class MarvelResultDataResultsEvents {
/*
{
  "available": 1,
  "collectionURI": "http://gateway.marvel.com/v1/public/characters/1011334/events",
  "items": [
    {
      "resourceURI": "http://gateway.marvel.com/v1/public/events/269",
      "name": "Secret Invasion"
    }
  ],
  "returned": 1
} 
*/

  int? available;
  String? collectionURI;
  List<MarvelResultDataResultsEventsItems?>? items;
  int? returned;

  MarvelResultDataResultsEvents({
    this.available,
    this.collectionURI,
    this.items,
    this.returned,
  });
  MarvelResultDataResultsEvents.fromJson(Map<String, dynamic> json) {
    available = json['available']?.toInt();
    collectionURI = json['collectionURI']?.toString();
    if (json['items'] != null) {
      final v = json['items'];
      final arr0 = <MarvelResultDataResultsEventsItems>[];
      v.forEach((v) {
        arr0.add(MarvelResultDataResultsEventsItems.fromJson(v));
      });
      items = arr0;
    }
    returned = json['returned']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['available'] = available;
    data['collectionURI'] = collectionURI;
    if (items != null) {
      final v = items;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['items'] = arr0;
    }
    data['returned'] = returned;
    return data;
  }
}

class MarvelResultDataResultsStoriesItems {
/*
{
  "resourceURI": "http://gateway.marvel.com/v1/public/stories/19947",
  "name": "Cover #19947",
  "type": "cover"
} 
*/

  String? resourceURI;
  String? name;
  String? type;

  MarvelResultDataResultsStoriesItems({
    this.resourceURI,
    this.name,
    this.type,
  });
  MarvelResultDataResultsStoriesItems.fromJson(Map<String, dynamic> json) {
    resourceURI = json['resourceURI']?.toString();
    name = json['name']?.toString();
    type = json['type']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['resourceURI'] = resourceURI;
    data['name'] = name;
    data['type'] = type;
    return data;
  }
}

class MarvelResultDataResultsStories {
/*
{
  "available": 21,
  "collectionURI": "http://gateway.marvel.com/v1/public/characters/1011334/stories",
  "items": [
    {
      "resourceURI": "http://gateway.marvel.com/v1/public/stories/19947",
      "name": "Cover #19947",
      "type": "cover"
    }
  ],
  "returned": 20
} 
*/

  int? available;
  String? collectionURI;
  List<MarvelResultDataResultsStoriesItems?>? items;
  int? returned;

  MarvelResultDataResultsStories({
    this.available,
    this.collectionURI,
    this.items,
    this.returned,
  });
  MarvelResultDataResultsStories.fromJson(Map<String, dynamic> json) {
    available = json['available']?.toInt();
    collectionURI = json['collectionURI']?.toString();
    if (json['items'] != null) {
      final v = json['items'];
      final arr0 = <MarvelResultDataResultsStoriesItems>[];
      v.forEach((v) {
        arr0.add(MarvelResultDataResultsStoriesItems.fromJson(v));
      });
      items = arr0;
    }
    returned = json['returned']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['available'] = available;
    data['collectionURI'] = collectionURI;
    if (items != null) {
      final v = items;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['items'] = arr0;
    }
    data['returned'] = returned;
    return data;
  }
}

class MarvelResultDataResultsSeriesItems {
/*
{
  "resourceURI": "http://gateway.marvel.com/v1/public/series/1945",
  "name": "Avengers: The Initiative (2007 - 2010)"
} 
*/

  String? resourceURI;
  String? name;

  MarvelResultDataResultsSeriesItems({
    this.resourceURI,
    this.name,
  });
  MarvelResultDataResultsSeriesItems.fromJson(Map<String, dynamic> json) {
    resourceURI = json['resourceURI']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['resourceURI'] = resourceURI;
    data['name'] = name;
    return data;
  }
}

class MarvelResultDataResultsSeries {
/*
{
  "available": 3,
  "collectionURI": "http://gateway.marvel.com/v1/public/characters/1011334/series",
  "items": [
    {
      "resourceURI": "http://gateway.marvel.com/v1/public/series/1945",
      "name": "Avengers: The Initiative (2007 - 2010)"
    }
  ],
  "returned": 3
} 
*/

  int? available;
  String? collectionURI;
  List<MarvelResultDataResultsSeriesItems?>? items;
  int? returned;

  MarvelResultDataResultsSeries({
    this.available,
    this.collectionURI,
    this.items,
    this.returned,
  });
  MarvelResultDataResultsSeries.fromJson(Map<String, dynamic> json) {
    available = json['available']?.toInt();
    collectionURI = json['collectionURI']?.toString();
    if (json['items'] != null) {
      final v = json['items'];
      final arr0 = <MarvelResultDataResultsSeriesItems>[];
      v.forEach((v) {
        arr0.add(MarvelResultDataResultsSeriesItems.fromJson(v));
      });
      items = arr0;
    }
    returned = json['returned']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['available'] = available;
    data['collectionURI'] = collectionURI;
    if (items != null) {
      final v = items;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['items'] = arr0;
    }
    data['returned'] = returned;
    return data;
  }
}

class MarvelResultDataResultsComicsItems {
/*
{
  "resourceURI": "http://gateway.marvel.com/v1/public/comics/21366",
  "name": "Avengers: The Initiative (2007) #14"
} 
*/

  String? resourceURI;
  String? name;

  MarvelResultDataResultsComicsItems({
    this.resourceURI,
    this.name,
  });
  MarvelResultDataResultsComicsItems.fromJson(Map<String, dynamic> json) {
    resourceURI = json['resourceURI']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['resourceURI'] = resourceURI;
    data['name'] = name;
    return data;
  }
}

class MarvelResultDataResultsComics {
/*
{
  "available": 12,
  "collectionURI": "http://gateway.marvel.com/v1/public/characters/1011334/comics",
  "items": [
    {
      "resourceURI": "http://gateway.marvel.com/v1/public/comics/21366",
      "name": "Avengers: The Initiative (2007) #14"
    }
  ],
  "returned": 12
} 
*/

  int? available;
  String? collectionURI;
  List<MarvelResultDataResultsComicsItems?>? items;
  int? returned;

  MarvelResultDataResultsComics({
    this.available,
    this.collectionURI,
    this.items,
    this.returned,
  });
  MarvelResultDataResultsComics.fromJson(Map<String, dynamic> json) {
    available = json['available']?.toInt();
    collectionURI = json['collectionURI']?.toString();
    if (json['items'] != null) {
      final v = json['items'];
      final arr0 = <MarvelResultDataResultsComicsItems>[];
      v.forEach((v) {
        arr0.add(MarvelResultDataResultsComicsItems.fromJson(v));
      });
      items = arr0;
    }
    returned = json['returned']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['available'] = available;
    data['collectionURI'] = collectionURI;
    if (items != null) {
      final v = items;
      final arr0 = [];
      v?.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['items'] = arr0;
    }
    data['returned'] = returned;
    return data;
  }
}

class MarvelResultDataResultsThumbnail {
/*
{
  "path": "http://i.annihil.us/u/prod/marvel/i/mg/c/e0/535fecbbb9784",
  "extension": "jpg"
} 
*/

  String? path;
  String? extension;

  MarvelResultDataResultsThumbnail({
    this.path,
    this.extension,
  });
  MarvelResultDataResultsThumbnail.fromJson(Map<String, dynamic> json) {
    path = json['path']?.toString();
    extension = json['extension']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['path'] = path;
    data['extension'] = extension;
    return data;
  }
}

class MarvelResultDataResults {
/*
{
  "id": 1011334,
  "name": "3-D Man",
  "description": "",
  "modified": "2014-04-29T14:18:17-0400",
  "thumbnail": {
    "path": "http://i.annihil.us/u/prod/marvel/i/mg/c/e0/535fecbbb9784",
    "extension": "jpg"
  },
  "resourceURI": "http://gateway.marvel.com/v1/public/characters/1011334",
  "comics": {
    "available": 12,
    "collectionURI": "http://gateway.marvel.com/v1/public/characters/1011334/comics",
    "items": [
      {
        "resourceURI": "http://gateway.marvel.com/v1/public/comics/21366",
        "name": "Avengers: The Initiative (2007) #14"
      }
    ],
    "returned": 12
  },
  "series": {
    "available": 3,
    "collectionURI": "http://gateway.marvel.com/v1/public/characters/1011334/series",
    "items": [
      {
        "resourceURI": "http://gateway.marvel.com/v1/public/series/1945",
        "name": "Avengers: The Initiative (2007 - 2010)"
      }
    ],
    "returned": 3
  },
  "stories": {
    "available": 21,
    "collectionURI": "http://gateway.marvel.com/v1/public/characters/1011334/stories",
    "items": [
      {
        "resourceURI": "http://gateway.marvel.com/v1/public/stories/19947",
        "name": "Cover #19947",
        "type": "cover"
      }
    ],
    "returned": 20
  },
  "events": {
    "available": 1,
    "collectionURI": "http://gateway.marvel.com/v1/public/characters/1011334/events",
    "items": [
      {
        "resourceURI": "http://gateway.marvel.com/v1/public/events/269",
        "name": "Secret Invasion"
      }
    ],
    "returned": 1
  },
  "urls": [
    {
      "type": "detail",
      "url": "http://marvel.com/comics/characters/1011334/3-d_man?utm_campaign=apiRef&utm_source=edc015b686b72ca236f9a3a730613076"
    }
  ]
} 
*/

  int? id;
  String? name;
  String? description;
  String? modified;
  MarvelResultDataResultsThumbnail? thumbnail;
  String? resourceURI;
  MarvelResultDataResultsComics? comics;
  MarvelResultDataResultsSeries? series;
  MarvelResultDataResultsStories? stories;
  MarvelResultDataResultsEvents? events;
  List<MarvelResultDataResultsUrls?>? urls;

  MarvelResultDataResults({
    this.id,
    this.name,
    this.description,
    this.modified,
    this.thumbnail,
    this.resourceURI,
    this.comics,
    this.series,
    this.stories,
    this.events,
    this.urls,
  });
  MarvelResultDataResults.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    description = json['description']?.toString();
    modified = json['modified']?.toString();
    thumbnail = (json['thumbnail'] != null)
        ? MarvelResultDataResultsThumbnail.fromJson(json['thumbnail'])
        : null;
    resourceURI = json['resourceURI']?.toString();
    comics = (json['comics'] != null)
        ? MarvelResultDataResultsComics.fromJson(json['comics'])
        : null;
    series = (json['series'] != null)
        ? MarvelResultDataResultsSeries.fromJson(json['series'])
        : null;
    stories = (json['stories'] != null)
        ? MarvelResultDataResultsStories.fromJson(json['stories'])
        : null;
    events = (json['events'] != null)
        ? MarvelResultDataResultsEvents.fromJson(json['events'])
        : null;
    if (json['urls'] != null) {
      final v = json['urls'];
      final arr0 = <MarvelResultDataResultsUrls>[];
      v.forEach((v) {
        arr0.add(MarvelResultDataResultsUrls.fromJson(v));
      });
      urls = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['description'] = description;
    data['modified'] = modified;
    if (thumbnail != null) {
      data['thumbnail'] = thumbnail!.toJson();
    }
    data['resourceURI'] = resourceURI;
    if (comics != null) {
      data['comics'] = comics!.toJson();
    }
    if (series != null) {
      data['series'] = series!.toJson();
    }
    if (stories != null) {
      data['stories'] = stories!.toJson();
    }
    if (events != null) {
      data['events'] = events!.toJson();
    }
    if (urls != null) {
      final v = urls;
      final arr0 = [];
      v?.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['urls'] = arr0;
    }
    return data;
  }

  @override
  String toString() {
    return 'MarvelResultDataResults(id: $id, name: $name, description: $description, modified: $modified, resourceURI: $resourceURI, urls: $urls)';
  }
}

class MarvelResultData {
/*
{
  "offset": 0,
  "limit": 20,
  "total": 1562,
  "count": 20,
  "results": [
    {
      "id": 1011334,
      "name": "3-D Man",
      "description": "",
      "modified": "2014-04-29T14:18:17-0400",
      "thumbnail": {
        "path": "http://i.annihil.us/u/prod/marvel/i/mg/c/e0/535fecbbb9784",
        "extension": "jpg"
      },
      "resourceURI": "http://gateway.marvel.com/v1/public/characters/1011334",
      "comics": {
        "available": 12,
        "collectionURI": "http://gateway.marvel.com/v1/public/characters/1011334/comics",
        "items": [
          {
            "resourceURI": "http://gateway.marvel.com/v1/public/comics/21366",
            "name": "Avengers: The Initiative (2007) #14"
          }
        ],
        "returned": 12
      },
      "series": {
        "available": 3,
        "collectionURI": "http://gateway.marvel.com/v1/public/characters/1011334/series",
        "items": [
          {
            "resourceURI": "http://gateway.marvel.com/v1/public/series/1945",
            "name": "Avengers: The Initiative (2007 - 2010)"
          }
        ],
        "returned": 3
      },
      "stories": {
        "available": 21,
        "collectionURI": "http://gateway.marvel.com/v1/public/characters/1011334/stories",
        "items": [
          {
            "resourceURI": "http://gateway.marvel.com/v1/public/stories/19947",
            "name": "Cover #19947",
            "type": "cover"
          }
        ],
        "returned": 20
      },
      "events": {
        "available": 1,
        "collectionURI": "http://gateway.marvel.com/v1/public/characters/1011334/events",
        "items": [
          {
            "resourceURI": "http://gateway.marvel.com/v1/public/events/269",
            "name": "Secret Invasion"
          }
        ],
        "returned": 1
      },
      "urls": [
        {
          "type": "detail",
          "url": "http://marvel.com/comics/characters/1011334/3-d_man?utm_campaign=apiRef&utm_source=edc015b686b72ca236f9a3a730613076"
        }
      ]
    }
  ]
} 
*/

  int? offset;
  int? limit;
  int? total;
  int? count;
  List<MarvelResultDataResults?>? results;

  MarvelResultData({
    this.offset,
    this.limit,
    this.total,
    this.count,
    this.results,
  });
  MarvelResultData.fromJson(Map<String, dynamic> json) {
    offset = json['offset']?.toInt();
    limit = json['limit']?.toInt();
    total = json['total']?.toInt();
    count = json['count']?.toInt();
    if (json['results'] != null) {
      final v = json['results'];
      final arr0 = <MarvelResultDataResults>[];
      v.forEach((v) {
        arr0.add(MarvelResultDataResults.fromJson(v));
      });
      results = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['offset'] = offset;
    data['limit'] = limit;
    data['total'] = total;
    data['count'] = count;
    if (results != null) {
      final v = results;
      final arr0 = [];
      v?.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['results'] = arr0;
    }
    return data;
  }
}

class MarvelResult {
/*
{
  "code": 200,
  "status": "Ok",
  "copyright": "© 2022 MARVEL",
  "attributionText": "Data provided by Marvel. © 2022 MARVEL",
  "attributionHTML": "<a href=\"http://marvel.com\">Data provided by Marvel. © 2022 MARVEL</a>",
  "etag": "d5ebfae93f05554f2b43766e44c58cbe55ed3246",
  "data": {
    "offset": 0,
    "limit": 20,
    "total": 1562,
    "count": 20,
    "results": [
      {
        "id": 1011334,
        "name": "3-D Man",
        "description": "",
        "modified": "2014-04-29T14:18:17-0400",
        "thumbnail": {
          "path": "http://i.annihil.us/u/prod/marvel/i/mg/c/e0/535fecbbb9784",
          "extension": "jpg"
        },
        "resourceURI": "http://gateway.marvel.com/v1/public/characters/1011334",
        "comics": {
          "available": 12,
          "collectionURI": "http://gateway.marvel.com/v1/public/characters/1011334/comics",
          "items": [
            {
              "resourceURI": "http://gateway.marvel.com/v1/public/comics/21366",
              "name": "Avengers: The Initiative (2007) #14"
            }
          ],
          "returned": 12
        },
        "series": {
          "available": 3,
          "collectionURI": "http://gateway.marvel.com/v1/public/characters/1011334/series",
          "items": [
            {
              "resourceURI": "http://gateway.marvel.com/v1/public/series/1945",
              "name": "Avengers: The Initiative (2007 - 2010)"
            }
          ],
          "returned": 3
        },
        "stories": {
          "available": 21,
          "collectionURI": "http://gateway.marvel.com/v1/public/characters/1011334/stories",
          "items": [
            {
              "resourceURI": "http://gateway.marvel.com/v1/public/stories/19947",
              "name": "Cover #19947",
              "type": "cover"
            }
          ],
          "returned": 20
        },
        "events": {
          "available": 1,
          "collectionURI": "http://gateway.marvel.com/v1/public/characters/1011334/events",
          "items": [
            {
              "resourceURI": "http://gateway.marvel.com/v1/public/events/269",
              "name": "Secret Invasion"
            }
          ],
          "returned": 1
        },
        "urls": [
          {
            "type": "detail",
            "url": "http://marvel.com/comics/characters/1011334/3-d_man?utm_campaign=apiRef&utm_source=edc015b686b72ca236f9a3a730613076"
          }
        ]
      }
    ]
  }
} 
*/

  int? code;
  String? status;
  String? copyright;
  String? attributionText;
  String? attributionHTML;
  String? etag;
  MarvelResultData? data;

  MarvelResult({
    this.code,
    this.status,
    this.copyright,
    this.attributionText,
    this.attributionHTML,
    this.etag,
    this.data,
  });
  MarvelResult.fromJson(Map<String, dynamic> json) {
    code = json['code']?.toInt();
    status = json['status']?.toString();
    copyright = json['copyright']?.toString();
    attributionText = json['attributionText']?.toString();
    attributionHTML = json['attributionHTML']?.toString();
    etag = json['etag']?.toString();
    data =
        (json['data'] != null) ? MarvelResultData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    data['status'] = status;
    data['copyright'] = copyright;
    data['attributionText'] = attributionText;
    data['attributionHTML'] = attributionHTML;
    data['etag'] = etag;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
