// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAIQ59olQGsH11RC4wJ810D9v94jX0g7o',
    appId: '1:358049174702:web:dc06ed164af0052c8b493f',
    messagingSenderId: '358049174702',
    projectId: 'firebase-authoc',
    authDomain: 'fir-authoc.firebaseapp.com',
    databaseURL: 'https://firebase-authoc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'firebase-authoc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO5h5Cp63kAVatZh81iCNM55rsP8Y0xAE',
    appId: '1:358049174702:android:9ac8bd56ef1a5d238b493f',
    messagingSenderId: '358049174702',
    projectId: 'firebase-authoc',
    databaseURL: 'https://firebase-authoc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'firebase-authoc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn33Bo6PTm7bHbM346DP9bPOx3b553zqA',
    appId: '1:358049174702:ios:2a1251c6c9d5d9268b493f',
    messagingSenderId: '358049174702',
    projectId: 'firebase-authoc',
    databaseURL: 'https://firebase-authoc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'firebase-authoc.appspot.com',
    iosBundleId: 'com.netix.stajProjectt',
  );
}
